name: Check Required Files

on: [push, pull_request]

jobs:
  check-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check if README.md exists
        run: |
          if [ ! -f README.md ]; then
            echo "❌ README.md is missing!"
            exit 1
          else
            echo "✅ README.md found!"
          fi

      - name: Check if .github/workflows exists
        run: |
          if [ ! -d .github/workflows ]; then
            echo "❌ .github/workflows directory is missing!"
            exit 1
          else
            echo "✅ .github/workflows directory found!"
          fi
