name: CI Pipeline

# Eventos que activan el workflow
on:
  push:
    branches:
      - main  # Se ejecuta al hacer push a la rama main
  pull_request:
    branches:
      - main  # Se ejecuta al crear un pull request hacia main

# Jobs que se ejecutan
jobs:
  test:
    runs-on: ubuntu-latest  # Usa un runner con Ubuntu

    steps:
      # Paso 1: Checkout del codigo
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Configurar el entorno (por ejemplo, Node.js)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Version de Node.js

      # Paso 3: Instalar dependencias
      - name: Install dependencies
        run: npm install

      # Paso 4: Ejecutar pruebas
      - name: Run tests
        run: npm test
